name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::104633066728:role/github-lambda-deployer
          aws-region: us-east-2

      - name: Package backfill Lambda
        run: |
          cd ingestion
          zip backfill.zip backfill_lambda.py

      - name: Deploy backfill Lambda
        run: |
          aws lambda update-function-code \
            --function-name sf-crime-backfill \
            --zip-file fileb://ingestion/backfill.zip

      - name: Package transform Lambda
        run: |
          cd transformation
          zip transform.zip transform_lambda.py

      - name: Deploy transform Lambda
        run: |
          aws lambda update-function-code \
            --function-name sf-crime-transform \
            --zip-file fileb://transformation/transform.zip

      # ----------------------------
      # Deploy Incremental Lambda
      # ----------------------------
      - name: Package incremental Lambda
        run: |
          cd ingestion
          zip incremental.zip incremental_lambda.py

      - name: Deploy incremental Lambda
        run: |
          aws lambda update-function-code \
            --function-name sf-crime-incremental \
            --zip-file fileb://ingestion/incremental.zip